# Generated by Django 4.0.10 on 2023-03-01 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_city_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления записи')),
                ('base', models.CharField(max_length=3, verbose_name='Валюта')),
                ('date', models.DateTimeField(verbose_name='Дата получения курсов')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления записи')),
                ('country', models.CharField(max_length=2, verbose_name='ISO Alpha2 country code')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('temp', models.FloatField(verbose_name='Температура, С')),
                ('pressure', models.IntegerField(verbose_name='Давление, мм. рт. ст.')),
                ('humidity', models.IntegerField(verbose_name='Влажность, %')),
                ('wind_speed', models.FloatField(verbose_name='Скорость ветра, м\\с')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Погода',
                'verbose_name_plural': 'Погода',
                'ordering': ['country', 'city'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления записи')),
                ('compared_to', models.CharField(max_length=3, verbose_name='Сравниваемая валюта')),
                ('value', models.FloatField(verbose_name='курс')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valute', to='geo.valute', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
