# Generated by Django 4.0.10 on 2023-03-01 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_valute_weather_currencyrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrate',
            name='date',
            field=models.DateTimeField(default=datetime.date(2023, 3, 1), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='base',
            field=models.CharField(max_length=3, verbose_name='Валюта'),
        ),
        migrations.DeleteModel(
            name='Valute',
        ),
    ]
