# Generated by Django 4.0.10 on 2023-03-01 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_currencyrate_date_alter_currencyrate_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 1), verbose_name='Дата'),
        ),
    ]
