# Generated by Django 4.0.10 on 2023-03-02 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_alter_currencyrate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='date',
            field=models.DateTimeField(default=datetime.date(2023, 3, 2), verbose_name='Дата'),
        ),
    ]
